"""
Sikhar Standalone Executable & Bundle Builder
Compiles and bundles Sikhar programs into standalone executable archives (.pyz and .bat).
"""

import os
import sys
import zipfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ..errors.error_types import SikharCompileError
from ..lexer.lexer import Lexer
from ..parser.parser import Parser
from ..vm.compiler import Compiler
from ..vm.serializer import serialize_chunk


def _get_sikhar_source_dir() -> Path:
    """Return the root path of the 'sikhar' package directory."""
    return Path(__file__).resolve().parent.parent


def build_standalone(
    entry_file: str,
    output_path: Optional[str] = None,
    use_vm: bool = True,
    create_wrapper: bool = True,
) -> Tuple[Path, Optional[Path]]:
    """
    Build a standalone, self-executing zipapp bundle for a Sikhar program.

    Args:
        entry_file: Path to the entry Sikhar source (.sk) or bytecode (.skc) file.
        output_path: Target path for the generated bundle. Defaults to <entry_name>.pyz.
        use_vm: If True, executes compiled bytecode on the VM; otherwise AST interpreter.
        create_wrapper: If True and on Windows (or specified), generates a .bat launcher.

    Returns:
        Tuple of (pyz_path, bat_wrapper_path_or_None)
    """
    entry_path = Path(entry_file).resolve()
    if not entry_path.exists():
        raise FileNotFoundError(f"Source file not found: {entry_file}")

    # Determine output paths
    if output_path:
        target_pyz = Path(output_path).resolve()
        if target_pyz.suffix.lower() != ".pyz":
            if target_pyz.suffix.lower() in (".exe", ".bat"):
                target_pyz = target_pyz.with_suffix(".pyz")
            else:
                target_pyz = Path(str(target_pyz) + ".pyz")
    else:
        target_pyz = entry_path.with_suffix(".pyz")

    target_pyz.parent.mkdir(parents=True, exist_ok=True)

    # Read source or bytecode
    bytecode_bytes: Optional[bytes] = None
    source_text: str = ""

    if entry_path.suffix.lower() == ".skc":
        bytecode_bytes = entry_path.read_bytes()
        use_vm = True
    else:
        source_text = entry_path.read_text(encoding="utf-8")
        try:
            tokens = Lexer(source_text, entry_path.name).tokenize()
            ast = Parser(tokens, source_text, entry_path.name).parse()
            if use_vm:
                chunk = Compiler(entry_path.name).compile(ast)
                bytecode_bytes = serialize_chunk(chunk)
        except Exception as e:
            raise SikharCompileError(f"Compilation failed during build: {e}", filename=str(entry_path))

    # Bootstrap entry script inside the archive
    main_py_content = f'''# Auto-generated by Sikhar Standalone Bundler (v1.0.0)
import sys
import os
from pathlib import Path

# Ensure bundled package is on import search path
_bundle_dir = str(Path(__file__).resolve().parent)
if _bundle_dir not in sys.path:
    sys.path.insert(0, _bundle_dir)

from sikhar.errors.error_types import SikharError
from sikhar.errors.reporter import print_error

USE_VM = {repr(use_vm)}
BYTECODE_DATA = {repr(bytecode_bytes)}
SOURCE_CODE = {repr(source_text)}
FILENAME = {repr(entry_path.name)}

def run():
    try:
        if USE_VM and BYTECODE_DATA:
            from sikhar.vm.serializer import deserialize_chunk
            from sikhar.vm.vm import VM
            chunk = deserialize_chunk(BYTECODE_DATA, FILENAME)
            vm = VM(source=SOURCE_CODE or "", filename=FILENAME)
            vm.run(chunk)
        else:
            from sikhar.lexer.lexer import Lexer
            from sikhar.parser.parser import Parser
            from sikhar.interpreter.interpreter import Interpreter
            tokens = Lexer(SOURCE_CODE, FILENAME).tokenize()
            ast = Parser(tokens, SOURCE_CODE, FILENAME).parse()
            Interpreter(filename=FILENAME).interpret(ast)
        sys.exit(0)
    except SikharError as err:
        print_error(err, SOURCE_CODE)
        sys.exit(1)
    except Exception as e:
        print(f"Sikhar Runtime Error: {{e}}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    run()
'''

    # Package the Sikhar runtime and the entry runner into zipapp
    sikhar_root = _get_sikhar_source_dir()

    with zipfile.ZipFile(target_pyz, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Write root __main__.py
        zf.writestr("__main__.py", main_py_content)

        # Recursively package all python files in sikhar package
        for root, dirs, files in os.walk(sikhar_root):
            # Skip caches and temporary directories
            dirs[:] = [d for d in dirs if d != "__pycache__" and not d.startswith(".")]
            for file in files:
                if file.endswith((".py", ".sk", ".json", ".txt")):
                    file_full_path = Path(root) / file
                    rel_to_sikhar = file_full_path.relative_to(sikhar_root)
                    archive_path = Path("sikhar") / rel_to_sikhar
                    zf.write(file_full_path, str(archive_path).replace("\\", "/"))

    # Create companion wrapper script (.bat) on Windows if requested
    bat_path: Optional[Path] = None
    if create_wrapper:
        bat_path = target_pyz.with_suffix(".bat")
        pyz_filename = target_pyz.name
        bat_content = f"""@echo off
setlocal
python "%~dp0{pyz_filename}" %*
exit /b %ERRORLEVEL%
"""
        bat_path.write_text(bat_content, encoding="utf-8")

    return target_pyz, bat_path
